spring:
  datasource:
    url: jdbc:mysql://222.192.6.62:3306/resources_class?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
  redis:
<<<<<<< HEAD
    password: fz123456,
    database: 3

=======
    password: fzsj@GIS
    database: 3
    host: 202.102.89.244
>>>>>>> upstream/main
# 跨域
registry:
  allowedOrigins: http://127.0.0.1:8080

neo4j:
  url: bolt://222.192.6.62:7687

file:
  root: E:\\TestResource

