# 运行端口
server:
  port: 9000

# 数据库配置
spring:
  profiles:
    active: dev
#    active: prod
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  #redis
  redis:
#    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 50
        min-idle: 20

# 整合mybatis
mybatis:
  type-aliases-package: cn.edu.njnu.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

neo4j:
  username: neo4j
  password: 123456
