# 运行端口
server:
  port: 9000

# 数据库配置
spring:
  datasource:
    username: root
    password: 123456
#    url: jdbc:mysql://222.192.6.62:3306/resources_class?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    url: jdbc:mysql://s4.z100.vip:8497/resources_class?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  neo4j:
    uri: http://127.0.0.1:7474
    authentication:
      username: neo4j
      password: 123456
# 整合mybatis
mybatis:
  type-aliases-package: cn.edu.njnu.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
