spring:
  datasource:
    url: jdbc:mysql://s4.z100.vip:8497/resources_class?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8

# 跨域
registry:
  allowedOrigins: http://202.102.89.244:9311

neo4j:
  url: bolt://s4.z100.vip:7687

file:
  root: E:\\e-resource\\TestResource
