# 运行端口
server:
  port: 9000


spring:
  profiles:
    active: dev
#    active: prod
  # 数据库配置
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
<<<<<<< HEAD
  # redis
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 50
        min-idle: 20
=======
  #redis
#  redis:
#    host: 222.192.6.62
#    port: 6379
#    jedis:
#      pool:
#        max-active: 50
#        min-idle: 20
>>>>>>> upstream/main

# 整合mybatis
mybatis:
  type-aliases-package: cn.edu.njnu.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

neo4j:
  username: neo4j
  password: 123456
